### ISSUE TITLE
HAML renderer can't find assets in packaged app.

### ISSUE THREAD

**Issue by jeremedia** [dennisbaskin/electron-view-renderer#11]
Trying to get HAML working. No problem rendering views during dev, but packaged apps can't find assets. 

`const viewRenderer = new ElectronViewRenderer({
  viewPath: 'views',
  viewProtcolName: 'view',
  useAssets: true,
  assetsPath: 'assets',
  assetsProtocolName: 'asset',
});`

`viewRenderer.add('haml', {
  extension: '.haml',
  viewPath: 'views',
  rendererAction: (filePath, viewData, callback) => {
    let hamlSrc = fs.readFileSync( path.join(__dirname,filePath), "utf8");
    let main = Haml(hamlSrc);
    let html = main(viewData);
    callback(html);
    }
});`

**Comment by jeremedia** [comment]
Including a full path to the assets fixed this.

`path.join(__dirname,'assets')`

**Comment by dennisbaskin** [comment]
@jeremedia where did you end up adding that to? Wondering if this is something that would be useful for others
