### ISSUE TITLE
Unable to require JS files using nodeIntegration with Electron.

### ISSUE THREAD

**Issue by markmorris** [dennisbaskin/electron-view-renderer#12]
So before installing this package i was able to require files in index.html as so...

```
<script>require('./renderer.js');</script>
```
i installed your package and set it up to use .pug which so so easy to do BTW (props for that). But including files in the template got broken, not sure why or where to start looking.

This is using pug, as you can see ive tried to add the asset:// (just like in your example for css) prefix but it still cant find the file. 
```
    script.
      require('asset://js/app.js');
```

**Comment by dennisbaskin** [comment]
Hi Mark, my apologies for the late reply. Could you please provide the node version and electron version so that I can try to reproduce this?

**Comment by dennisbaskin** [comment]
I created a quick example and was able to get this to work by using:

```
script.require(src='asset://js/app.js')
```
