### ISSUE TITLE
Loading external modules

### ISSUE THREAD

**Issue by devunivers** [dennisbaskin/electron-view-renderer#14]
hello
I can't load the my own modules
ex:  const stats = require('asset://libs/libs_stats')

**Comment by dennisbaskin** [comment]
As far as I remember, the protocols do not apply to your js source code. The usage is specific to the view files. I am assuming you are calling this in the js files?

**Comment by devunivers** [comment]
> As far as I remember, the protocols do not apply to your js source code. The usage is specific to the view files. I am assuming you are calling this in the js files?

yes, but i found a way to call libs with [module-alias](https://www.npmjs.com/package/module-alias) library, thank you for your answer

**Comment by dennisbaskin** [comment]
Awesome! closing issue
